name: Maven Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests and generate coverage report
        run: mvn test org.jacoco:jacoco-maven-plugin:report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-java-${{ matrix.java }}
          path: target/site/jacoco/
          retention-days: 14
          compression-level: 9
          overwrite: true